### ISSUE TITLE
Invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ni5arga** [ExhibitHQ/join-the-community#1]
### Name

Nisarga Adhikary

### Discord Username (if applicable)

ni5arga#3080

### Twiiter username (if applicable)

ni5arga

**Comment by Arindam200** [comment]
Hey @ni5arga ! 

Welcome to the organization!

**Comment by ni5arga** [comment]
thanks, glad to be here

**Comment by sammaji** [comment]
Welcome to our community @ni5arga

We're sending you an invite ✨
