### ISSUE TITLE
Invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Gallantfarhan** [ExhibitHQ/join-the-community#4]
### Name

Gallant farhan

### Discord Username (if applicable)

gallantfarhan#4075

### Twiiter username (if applicable)

Gallantfarhan

### Additional Context

wanted to join ExhibitHQ because to engage with the community members, learn from their experiences, and contribute my knowledge and assistance wherever possible. I believe that by being part of this community, I can provide helpful and insightful responses to questions, spark meaningful discussions.

**Comment by sammaji** [comment]
Welcome to the community @Gallantfarhan

**Comment by Gallantfarhan** [comment]
thanks for letting me join your community.
