### ISSUE TITLE
Invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by vishnu9865** [ExhibitHQ/join-the-community#5]
### Name

Jeyavishnu S

### Discord Username (if applicable)

Jeyavishnu S#2211

### Twiiter username (if applicable)

Jvishnu9865

### Additional Context

 - I discovered this community through fellow contributors from GirlScipt Summer of Code.
 - I want to join this esteemed community to contribute and learn as well as help other fellow member through guidance and support to the best of my abilities.

**Comment by sammaji** [comment]
Welcome to the community 🥳

You can also join our [discord](https://discord.gg/u6MmQqHg) server.
